#26: Zoltan2: MatrixAdapter refactor API
NexGenAnalytics/Trilinos pull request #49
Opened 2023-07-17 16:50 UTC by cwschilly

Fixes #26 and adds TpetraCrsMatrixAdapter

2023-07-17 18:32 UTC, cwschilly commented
This PR is almost ready for review; I just want to run it using the `graph.cpp` example to make sure everything works as expected (this example requires use of TPL's that I haven't installed yet)

2023-07-18 19:34 UTC, cwschilly commented
Since the `doMigration()` method was originally defined in `XpetraTraits.hpp`, and there is no corresponding `TpetraTraits` file, it had to be redefined within the new `TpetraCrsMatrixAdapter.hpp`. It is also defined in `TpetraRowMatrixAdapter.hpp`, but I considered this duplication to be the best option to minimize changes to external API.

2023-07-31 14:10 UTC, stmcgovern requested changes
looks good - please fix the new lines issue

2023-07-31 14:10 UTC, stmcgovern commented on packages/zoltan2/core/src/input/Zoltan2_TpetraCrsMatrixAdapter.hpp
> +#endif
This file (and a couple others) drops the trailing new line. Let's not change that, please.

2023-07-31 14:10 UTC, stmcgovern commented on packages/zoltan2/core/src/input/Zoltan2_XpetraCrsMatrixAdapter.hpp
> +#endif
lost new line again.

2023-07-31 14:10 UTC, stmcgovern commented on packages/zoltan2/test/core/helpers/Zoltan2_TestHelpers.hpp
> +#endif
lost new line again

2023-07-31 14:10 UTC, stmcgovern commented on packages/zoltan2/test/core/unit/input/TpetraCrsMatrixInput.cpp
> +  }
please add new line

2023-07-31 14:10 UTC, stmcgovern commented on packages/zoltan2/test/core/unit/input/TpetraRowMatrixInput.cpp
> +  }
new line needed

2023-07-31 15:09 UTC, JacobDomagala commented
I believe the changes will break NGA-develop branch. Please rebase with recent changes to NGA-develop and fix compilation errors

2023-07-31 15:19 UTC, JacobDomagala commented
See https://github.com/NexGenAnalytics/Trilinos/commit/e066b2f8200d2ba533595516e302f5ec70b34754 for reference on how to deal with Weights getters (we want to support both 2D and 1D versions - https://github.com/NexGenAnalytics/Trilinos/issues/14#issuecomment-1651878217)

2023-07-31 16:52 UTC, cwschilly commented on packages/zoltan2/core/src/input/Zoltan2_TpetraCrsMatrixAdapter.hpp
> +#endif
done

2023-07-31 16:52 UTC, cwschilly commented on packages/zoltan2/core/src/input/Zoltan2_XpetraCrsMatrixAdapter.hpp
> +#endif
done

2023-07-31 16:53 UTC, cwschilly commented on packages/zoltan2/test/core/unit/input/TpetraCrsMatrixInput.cpp
> +  }
done

2023-07-31 16:53 UTC, cwschilly commented on packages/zoltan2/test/core/unit/input/TpetraRowMatrixInput.cpp
> +  }
done

2023-08-01 15:41 UTC, stmcgovern approved these changes
It passes local tests with the new API. Thanks @cwschilly!

2023-08-01 15:41 UTC, merged